=== thanhndh/cameraip/chi_cdk/cdk/chromatix/XSD/stats/aec/aecIr.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--========================================================================-->
<!-- Copyright (c) 2018-2019 Qualcomm Technologies, Inc.                    -->
<!-- All Rights Reserved.                                                   -->
<!-- Confidential and Proprietary - Qualcomm Technologies, Inc.             -->
<!--========================================================================-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="..\..\common\globalelements.xsd"/>
	<xs:include schemaLocation="aecglobalelements.xsd"/>

	<xs:element name="aecIr" type="AECIRType" />
	<xs:complexType name="AECIRType">
		<xs:sequence>
			<xs:element name="module_version">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="major_revision" type="xs:int" fixed="1" />
						<xs:element name="minor_revision" type="xs:int" fixed="0" />
						<xs:element name="incr_revision" type="xs:int" fixed="0" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="IrMtr" type="IRMeteringType" />
			<xs:element name="IrConv" type="IRConvergenceType" />
			<xs:element name="IrArb" type="IRArbitrationType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IRMeteringType">
		<xs:sequence>
			<xs:element name="enableIR" default="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:boolean">
							<xs:attribute name="type" default="bool" />
							<xs:attribute name="description" default="Flag to enable IR mode AEC" type="xs:string" />
							<xs:attribute name="default_value" default="0" type="xs:string" />
							<xs:attribute name="range" default="[0, 1]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="must_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="weightTables" type="WeightTableType"/>
			<xs:element name="vlDetect" type="VisiblelightDetectType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IRLedAdjType">
		<xs:sequence>
			<xs:element name="enableIRled" default="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:boolean">
							<xs:attribute name="type" default="bool" />
							<xs:attribute name="description" default="Flag to enable IR LED support" type="xs:string" />
							<xs:attribute name="range" default="[0, 1]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="must_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="minLedIntensityIdx" default="1.0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="Minimum IR LED intensity Index" type="xs:string" />
							<xs:attribute name="range" default="[0,100]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="maxLedIntensityIdx" default="90.0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="Maximum IR LED intensity Index" type="xs:string" />
							<xs:attribute name="range" default="[0,100]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="ledIntensityUnit" default="1.0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="IR LED intensity percentage unit per Index" type="xs:string" />
							<xs:attribute name="range" default="[0,10]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IRAlsAdjType">
		<xs:sequence>
			<xs:element name="enableAls" default="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:boolean">
							<xs:attribute name="type" default="bool" />
							<xs:attribute name="description" default="Flag to enable IR ALS support" type="xs:string" />
							<xs:attribute name="range" default="[0, 1]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="must_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="day2irSwitchPt" default="100.0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="The value of ALS to switch day mode to ir mode" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="ir2daySwitchPt" default="1000.0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="The value of ALS to switch ir mode to day mode" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WeightTableType">
		<xs:sequence>
			<xs:element name="centerWeighted">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="weights">
							<xs:simpleType>
								<xs:restriction base="floatvar">
									<xs:length value="256"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="type" default="float"/>
					<xs:attribute name="description" default="Center weighted metering weight table."/>
					<xs:attribute name="range" default="[0,1]"/>
					<xs:attribute name="length" type="xs:int" fixed="256"/>
					<xs:attribute name="tuning_parameter_level" type="tuning_level" default="often_tune"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="LumaWeighted">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="weights">
							<xs:simpleType>
								<xs:restriction base="floatvar">
									<xs:length value="64"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="type" default="float"/>
					<xs:attribute name="description" default="Highlight suppress weight table."/>
					<xs:attribute name="range" default="[0,1]"/>
					<xs:attribute name="length" type="xs:int" fixed="64"/>
					<xs:attribute name="tuning_parameter_level" type="tuning_level" default="often_tune"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IRConvergenceType">
		<xs:sequence>
			<xs:element name="irSkipFrameCnt" default="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="type" default="int" />
							<xs:attribute name="description" default="Skip frames of AEC after IR cut switched" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="rarely_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="convSpeedAdjRatio" default="1.0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="Specify the adjustment of convergence speed during IR AEC convergence" type="xs:string" />
							<xs:attribute name="range" default="[0.0, 1.0]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="VisiblelightDetectType">
		<xs:sequence>
			<xs:element name="enable" default="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:boolean">
							<xs:attribute name="type" default="bool" />
							<xs:attribute name="description" default="Flag to enable visible light detection" type="xs:string" />
							<xs:attribute name="range" default="[0, 1]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="must_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="visibleLightCntThres" default="0.3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="Count threshold of visible light detection" type="xs:string" />
							<xs:attribute name="range" default="[0, 1]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="visibleLightTargetThres" default="0.5">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="Target threshold of visible light detection" type="xs:string" />
							<xs:attribute name="range" default="[0, 1]" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="irLightRangeBG" minOccurs="2" maxOccurs="2">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float"/>
							<xs:attribute name="description" type="xs:string" default="BG ratio to detect visible light."/>
							<xs:attribute name="tuning_parameter_level" type="tuning_level" default="rarely_tune"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="irLightRangeRG" minOccurs="2" maxOccurs="2">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float"/>
							<xs:attribute name="description" type="xs:string" default="RG ratio to detect visible light."/>
							<xs:attribute name="tuning_parameter_level" type="tuning_level" default="rarely_tune"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="irLightRangeRB" minOccurs="2" maxOccurs="2">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float"/>
							<xs:attribute name="description" type="xs:string" default="RB ratio to detect visible light."/>
							<xs:attribute name="tuning_parameter_level" type="tuning_level" default="rarely_tune"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="wTable">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="weights">
							<xs:simpleType>
								<xs:restriction base="floatvar">
									<xs:length value="256"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="type" default="float"/>
					<xs:attribute name="description" default="Weight table for detecting visible light."/>
					<xs:attribute name="range" default="[0,1]"/>
					<xs:attribute name="length" type="xs:int" fixed="256"/>
					<xs:attribute name="tuning_parameter_level" type="tuning_level" default="rarely_tune"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IRArbitrationType">
		<xs:sequence>
			<xs:element name="day2irCheckExpIdx" default="224.0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="Day to IR exp_index to trigger IR LED" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="ir2dayCheckExpIdx" default="184.0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:float">
							<xs:attribute name="type" default="float" />
							<xs:attribute name="description" default="IR to Day exp_index to turn off IR LED" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="often_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="day2irCheckCnt" default="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="type" default="int" />
							<xs:attribute name="description" default="Stable count while switching Day to IR mode" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="rarely_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="ir2dayCheckCnt" default="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="type" default="int" />
							<xs:attribute name="description" default="Stable count while switching IR to Day mode" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="rarely_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="irSwitchCheckSkipCnt" default="5">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="type" default="int" />
							<xs:attribute name="description" default="Check period of Day/Night switch" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="rarely_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="irSwitchChangeSkipCnt" default="30">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="type" default="int" />
							<xs:attribute name="description" default="Check period after Day/Night switched" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="rarely_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="irDriverType" default="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="type" default="int" />
							<xs:attribute name="description" default="LED driver control type: GPIO:0, PWM:1" type="xs:string" />
							<xs:attribute name="tuning_parameter_level" default="rarely_tune" type="tuning_level" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="irLedAdj" type="IRLedAdjType"/>
			<xs:element name="irAlsAdj" type="IRAlsAdjType"/>		
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== thanhndh/cameraip/chi_cdk/cdk/chromatix/XML/STATS/aecIr.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
========================================================================
   Copyright(c) 2018-2019 Qualcomm Technologies, Inc.
   All Rights Reserved.
   Confidential and Proprietary - Qualcomm Technologies, Inc.
========================================================================
-->
<aecIr
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="..\..\XSD\stats\aec\aecIr.xsd">
	<module_version>
        <major_revision>1</major_revision>
        <minor_revision>0</minor_revision>
        <incr_revision>0</incr_revision>
	</module_version>
	<IrMtr>
        <enableIR type="bool" description="Flag to enable IR mode AEC" default_value="1" range="[0, 1]" tuning_parameter_level="must_tune" >1</enableIR>
		<weightTables>
			<centerWeighted description="Center weighted weight table." range="[0,1]" length="256" tuning_parameter_level="often_tune">
				<weights>0.1016 0.10333 0.10822 0.11542 0.12369 0.1316 0.13778 0.14116 0.14116 0.13778 0.1316 0.12369 0.11542 0.10822 0.10333 0.1016 0.10333 0.10693 0.1171 0.13208 0.14929 0.16575 0.17861 0.18565 0.18565 0.17861 0.16575 0.14929 0.13208 0.1171 0.10693 0.10333 0.10822 0.1171 0.1422 0.17919 0.22167 0.26229 0.29404 0.31141 0.31141 0.29403 0.26229 0.22167 0.17919 0.1422 0.1171 0.10822 0.11542 0.13208 0.17919 0.2486 0.32831 0.40454 0.4641 0.4967 0.4967 0.4641 0.40454 0.32831 0.2486 0.17919 0.13208 0.11542 0.12369 0.14929 0.22167 0.32831 0.45078 0.56789 0.6594 0.70949 0.70949 0.6594 0.56789 0.45077 0.32831 0.22167 0.14929 0.12369 0.1316 0.16575 0.26229 0.40454 0.56789 0.7241 0.84617 0.91297 0.91297 0.84616 0.7241 0.56789 0.40453 0.26229 0.16575 0.1316 0.13778 0.17861 0.29404 0.4641 0.6594 0.84617 0.9921 1 1 0.9921 0.84616 0.65939 0.4641 0.29403 0.17861 0.13778 0.14116 0.18565 0.31141 0.4967 0.70949 0.91297 1 1 1 1 0.91296 0.70948 0.49669 0.3114 0.18564 0.14116 0.14116 0.18565 0.31141 0.4967 0.70949 0.91297 1 1 1 1 0.91296 0.70948 0.49669 0.3114 0.18564 0.14116 0.13778 0.17861 0.29403 0.4641 0.6594 0.84616 0.9921 1 1 0.99209 0.84616 0.65939 0.46409 0.29403 0.17861 0.13778 0.1316 0.16575 0.26229 0.40454 0.56789 0.7241 0.84616 0.91296 0.91296 0.84616 0.72409 0.56788 0.40453 0.26229 0.16575 0.1316 0.12369 0.14929 0.22167 0.32831 0.45077 0.56789 0.65939 0.70948 0.70948 0.65939 0.56788 0.45077 0.32831 0.22167 0.14929 0.12369 0.11542 0.13208 0.17919 0.2486 0.32831 0.40453 0.4641 0.49669 0.49669 0.46409 0.40453 0.32831 0.2486 0.17919 0.13208 0.11542 0.10822 0.1171 0.1422 0.17919 0.22167 0.26229 0.29403 0.3114 0.3114 0.29403 0.26229 0.22167 0.17919 0.1422 0.1171 0.10822 0.10333 0.10693 0.1171 0.13208 0.14929 0.16575 0.17861 0.18564 0.18564 0.17861 0.16575 0.14929 0.13208 0.1171 0.10693 0.10333 0.1016 0.10333 0.10822 0.11542 0.12369 0.1316 0.13778 0.14116 0.14116 0.13778 0.1316 0.12369 0.11542 0.10822 0.10333 0.1016</weights>
			</centerWeighted>
			<LumaWeighted description="Highlight suppress weight table." range="[0,1]" length="64" tuning_parameter_level="often_tune">
				<weights>0.20 0.20 0.20 0.20 0.20 0.20 0.20 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 </weights>
			</LumaWeighted>
		</weightTables>
		<vlDetect>
			<enable type="bool" description="Flag to enable visible light distribution detection" tuning_parameter_level="must_tune">1</enable>
			<visibleLightCntThres type="float" description="Count threshold of visible light detection" range="[0,1]" tuning_parameter_level="often_tune">0.3</visibleLightCntThres>
			<visibleLightTargetThres type="float" description="Target threshold of visible light detection" range="[0,100]" tuning_parameter_level="often_tune">26</visibleLightTargetThres>
			<irLightRangeBG description="BG ratio to detect visible light. " tuning_parameter_level="rarely_tune">0.93</irLightRangeBG>
			<irLightRangeBG description="BG ratio to detect visible light. " tuning_parameter_level="rarely_tune">1.07</irLightRangeBG>
			<irLightRangeRG description="RG ratio to detect visible light. " tuning_parameter_level="rarely_tune">0.93</irLightRangeRG>
			<irLightRangeRG description="RG ratio to detect visible light. " tuning_parameter_level="rarely_tune">1.07</irLightRangeRG>
			<irLightRangeRB description="RB ratio to detect visible light. " tuning_parameter_level="rarely_tune">0.90</irLightRangeRB>
			<irLightRangeRB description="RB ratio to detect visible light. " tuning_parameter_level="rarely_tune">1.10</irLightRangeRB>
			<wTable description="Weight table for detecting visible light." range="[0,1]" length="256" tuning_parameter_level="rarely_tune">
				<weights>0.1016 0.10333 0.10822 0.11542 0.12369 0.1316 0.13778 0.14116 0.14116 0.13778 0.1316 0.12369 0.11542 0.10822 0.10333 0.1016 0.10333 0.10693 0.1171 0.13208 0.14929 0.16575 0.17861 0.18565 0.18565 0.17861 0.16575 0.14929 0.13208 0.1171 0.10693 0.10333 0.10822 0.1171 0.1422 0.17919 0.22167 0.26229 0.29404 0.31141 0.31141 0.29403 0.26229 0.22167 0.17919 0.1422 0.1171 0.10822 0.11542 0.13208 0.17919 0.2486 0.32831 0.40454 0.4641 0.4967 0.4967 0.4641 0.40454 0.32831 0.2486 0.17919 0.13208 0.11542 0.12369 0.14929 0.22167 0.32831 0.45078 0.56789 0.6594 0.70949 0.70949 0.6594 0.56789 0.45077 0.32831 0.22167 0.14929 0.12369 0.1316 0.16575 0.26229 0.40454 0.56789 0.7241 0.84617 0.91297 0.91297 0.84616 0.7241 0.56789 0.40453 0.26229 0.16575 0.1316 0.13778 0.17861 0.29404 0.4641 0.6594 0.84617 0.9921 1 1 0.9921 0.84616 0.65939 0.4641 0.29403 0.17861 0.13778 0.14116 0.18565 0.31141 0.4967 0.70949 0.91297 1 1 1 1 0.91296 0.70948 0.49669 0.3114 0.18564 0.14116 0.14116 0.18565 0.31141 0.4967 0.70949 0.91297 1 1 1 1 0.91296 0.70948 0.49669 0.3114 0.18564 0.14116 0.13778 0.17861 0.29403 0.4641 0.6594 0.84616 0.9921 1 1 0.99209 0.84616 0.65939 0.46409 0.29403 0.17861 0.13778 0.1316 0.16575 0.26229 0.40454 0.56789 0.7241 0.84616 0.91296 0.91296 0.84616 0.72409 0.56788 0.40453 0.26229 0.16575 0.1316 0.12369 0.14929 0.22167 0.32831 0.45077 0.56789 0.65939 0.70948 0.70948 0.65939 0.56788 0.45077 0.32831 0.22167 0.14929 0.12369 0.11542 0.13208 0.17919 0.2486 0.32831 0.40453 0.4641 0.49669 0.49669 0.46409 0.40453 0.32831 0.2486 0.17919 0.13208 0.11542 0.10822 0.1171 0.1422 0.17919 0.22167 0.26229 0.29403 0.3114 0.3114 0.29403 0.26229 0.22167 0.17919 0.1422 0.1171 0.10822 0.10333 0.10693 0.1171 0.13208 0.14929 0.16575 0.17861 0.18564 0.18564 0.17861 0.16575 0.14929 0.13208 0.1171 0.10693 0.10333 0.1016 0.10333 0.10822 0.11542 0.12369 0.1316 0.13778 0.14116 0.14116 0.13778 0.1316 0.12369 0.11542 0.10822 0.10333 0.1016</weights>
			</wTable>
		</vlDetect>
	</IrMtr>
	<IrConv>
        <irSkipFrameCnt type="int" description="Skip frames of AEC after IR cut switched." tuning_parameter_level="rarely_tune">3</irSkipFrameCnt>
        <convSpeedAdjRatio type="float" description="Specify the adjustment of convergence speed during IR AEC convergence" range="[0.0, 1.0]" tuning_parameter_level="often_tune">1.00</convSpeedAdjRatio>
	</IrConv>
	<IrArb>
		<day2irCheckExpIdx type="float" description="Day to IR exp_index to trigger IR LED" tuning_parameter_level="often_tune">320.0</day2irCheckExpIdx>
		<ir2dayCheckExpIdx type="float" description="IR to Day exp_index to turn off IR LED" tuning_parameter_level="often_tune">270.0</ir2dayCheckExpIdx>
		<day2irCheckCnt type="int" description="Stable count while switching Day to IR mode." tuning_parameter_level="rarely_tune">3</day2irCheckCnt>
		<ir2dayCheckCnt type="int" description="Stable count while switching IR to Day mode." tuning_parameter_level="rarely_tune">3</ir2dayCheckCnt>
		<irSwitchCheckSkipCnt type="int" description="Check period of Day/Night switch." tuning_parameter_level="rarely_tune">5</irSwitchCheckSkipCnt>
		<irSwitchChangeSkipCnt type="int" description="Check period after Day/Night switched." tuning_parameter_level="rarely_tune">30</irSwitchChangeSkipCnt>
		<irDriverType type="int" description="LED driver control type: GPIO:0, PWM:1" tuning_parameter_level="rarely_tune">0</irDriverType>
		<irLedAdj>
			<enableIRled type="bool" description="Flag to enable IR LED support" tuning_parameter_level="must_tune">1</enableIRled>
			<minLedIntensityIdx type="float" description="Minimum IR LED intensity Index" range="[0,100]" tuning_parameter_level="often_tune">1.0</minLedIntensityIdx>
			<maxLedIntensityIdx type="float" description="Maximum IR LED intensity Index" range="[0,100]" tuning_parameter_level="often_tune">90.0</maxLedIntensityIdx>
			<ledIntensityUnit type="float" description="IR LED intensity percentage unit per Index" range="[0,100]" tuning_parameter_level="often_tune">1.0</ledIntensityUnit>		  
		</irLedAdj>
		<irAlsAdj>
			<enableAls type="bool" description="Flag to enable IR ALS support" tuning_parameter_level="must_tune">1</enableAls>
			<day2irSwitchPt type="float" description="The value of ALS to switch day mode to ir mode" tuning_parameter_level="often_tune">100.0</day2irSwitchPt>
			<ir2daySwitchPt type="float" description="The value of ALS to switch ir mode to day mode" tuning_parameter_level="often_tune">1000.0</ir2daySwitchPt>		  
		</irAlsAdj>
	</IrArb>
</aecIr>
